version: '3.2'
services:
  herenounce:
    build:
      context: ./
    ports:
     - "8010:80"
    volumes:
     - ./HereNounce/:/app
  helix:
    build:
      context: ./
    ports:
     - "8011:80"
    volumes:
     - ./Helix/:/app
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    #ports:
    #  - '3306:3306'
    #expose:
    #  - '3306'
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume: