version: '3.2'
services:
  herenounce:
    build:
      context: ./HereNounce/
    ports:
     - "${PORT_HERENOUNCE}:80"
    volumes:
     - ./HereNounce/:/app
    environment:
      HERENOUNCE_HOSTNAME: '${HERENOUNCE_HOSTNAME}'
      DB_USER: '${DB_USER}'
      DB_PASS: '${DB_PASS}'
      DB_NAME: '${DB_NAME}'
  helix:
    build:
      context: ./Helix/
    ports:
     - "${PORT_HELIX}:80"
    volumes:
     - ./Helix/:/app
    environment:
      HERENOUNCE_DOMAIN: '${HERENOUNCE_DOMAIN}'
      HERENOUNCE_HOSTNAME: '${HERENOUNCE_HOSTNAME}'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
    volumes:
      - ./storage/db:/var/lib/mysql