version: '3.2'
services:
  herenounce:
    build:
      context: ./
    ports:
     - "${PORT_HERENOUNCE}:80"
    volumes:
     - ./HereNounce/:/app
  helix:
    build:
      context: ./
    ports:
     - "${PORT_HELIX}:80"
    volumes:
     - ./Helix/:/app
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
    #ports:
    #  - '3306:3306'
    #expose:
    #  - '3306'
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume: